---
title: "prac5"
output: html_document
editor_options: 
  chunk_output_type: console
---
# Notes

*bedrooms is at ward -convert to borough</p>
*could also probably just use local Area District Data</p>
*Hotel is poly -summarise over borough</p>
*Airbnb is points - summarise over borough</p>


```{r library}

library(sf)
library(tmap)
library(tmaptools)
library(tidyverse)
library(here)
library(janitor)
library(tmap)
library(tmaptools)
library(rgl)
```

```{read ward data}
#London Borough data is already in 277000
Londonborough <- st_read(here::here("Data",
                                    "statistical-gis-boundaries-london", 
                                    "ESRI", 
                                    "London_Borough_Excluding_MHW.shp"))%>%
                           clean_names()%>%
  st_transform(., 27700)

Londonwards <- st_read(here::here("Data",
                                  "statistical-gis-boundaries-london", 
                                  "ESRI", 
                                  "London_Ward.shp"))%>%
                           clean_names()%>%
  st_transform(., 27700)

```


```{read accomodation data}
OSM <- st_read(here::here("Data",
                          "greater-london-latest-free.shp", 
                          "gis_osm_pois_a_free_1.shp")) %>%
  st_transform(., 27700)

Worldcities <- st_read(here::here("Data", 
                                  "World_Cities", 
                                  "World_Cities.shp")) %>%
  st_transform(., 27700)


# read in the .csv
# and make it into spatial data
Airbnb <- read_csv("Data/listings.csv") %>%
  st_as_sf(., coords = c("longitude", "latitude"), 
                   crs = 4326) %>%
    st_transform(., 27700)

ward_beds <- read_csv("Data/Number of bedrooms.csv") %>%
                           clean_names()
  
```

```{r bed to borough}
beds_borough <- Londonwards %>%
  left_join(.,
            ward_beds,
            by = c("gss_code" = "geography_code")) %>%
  group_by(lb_gss_cd,borough) %>%
  summarise(total_beds_per_borough=sum(bedrooms_all_categories_number_of_bedrooms_measures_value,na.rm = TRUE))%>%
  st_drop_geometry()

```

```{Airbnb_borough}
Airbnb_borough <- Airbnb %>%
  filter(room_type == 'Entire home/apt' & availability_365 =='365') %>%
  st_join(Londonborough,.)%>%
  group_by(gss_code)%>%
  summarise(airbnbcount=n())%>%
  st_drop_geometry()


```

```{r osm_hotels}
OSM_hotels <- OSM %>%
  filter(fclass =="hotel") %>%
  st_join(Londonborough,.)%>%
  group_by(gss_code)%>%
  summarise(hotelcount=n())%>%
  st_drop_geometry()
```

```{r combine data}
all_data_one <- Londonborough%>%
  left_join(.,
            beds_borough,
            by = c("gss_code" = "lb_gss_cd"))

all_data_two <- all_data_one%>%
  left_join(.,
            Airbnb_borough,
            by = c("gss_code" = "gss_code"))

all_data_three <- all_data_two%>%
  left_join(.,
            OSM_hotels,
            by = c("gss_code" = "gss_code"))

mapnorm <- all_data_three%>%
  mutate(airbnb_norm=airbnbcount/total_beds_per_borough)%>%
  mutate(hotel_norm=hotelcount/total_beds_per_borough)
  
```

```{r UK main cities}
Worldcities2 <- Worldcities %>%
  filter(CNTRY_NAME=='United Kingdom'&
           Worldcities$CITY_NAME=='Birmingham'|
           Worldcities$CITY_NAME=='London'|
           Worldcities$CITY_NAME=='Edinburgh')

```

```{UK outline}
UK_outline <- st_read(here::here("Data", 
                                 "gadm36_GBR_shp", 
                                 "gadm36_GBR_0.shp")) %>%
  st_transform(., 27700)
```


```{r mapping}
tmap_mode("plot")

tm1 <- tm_shape(mapnorm) + 
  tm_polygons("airbnb_norm", 
              style="jenks",
              palette="PuBu")+
  #tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(a)", position=c(0,0.85), size=1.5)

tm2 <- tm_shape(mapnorm) + 
  tm_polygons("hotel_norm",
              style="jenks", 
              palette="PuBu") + 
 # tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(b)", position=c(0,0.85), size=1.5)
  
newbb <- c(xmin=-296000, ymin=5408, xmax=655696, ymax=1000000)

UK_outlinecrop <- UK_outline$geometry %>%
  st_crop(., newbb)

tm3 <- tm_shape(UK_outlinecrop)+ 
  tm_polygons(col="darkslategray1")+
  tm_layout(frame=TRUE)+
  tm_shape(Worldcities2) +
  tm_symbols(col = "red", scale = .5)+
  tm_text("CITY_NAME", xmod=-1, ymod=-0.5)

legend <- tm_shape(mapnorm) +
    tm_polygons("hotel_norm",
                style="jenks", 
                palette="PuBu") +
    tm_scale_bar(position=c(0.2,0.04), text.size=0.6)+
    tm_compass(north=0, position=c(0.65,0.6))+
    tm_layout(legend.only = TRUE, legend.position=c(0.2,0.25),asp=0.1)+
    tm_credits("(c) OpenStreetMap contrbutors and Air b n b", position=c(0.0,0.0))

t=tmap_arrange(tm1, tm2, tm3, legend, ncol=2)
t

```

```{r inset map}

Londonbb = st_bbox(mapnorm)%>%
    st_as_sfc()
tmmain<- tm_shape(mapnorm, bbox=Londonbb)+
  tm_polygons("airbnb_norm", 
              style="jenks", 
              palette="PuBu")+
  tm_scale_bar(position = c("left", "bottom"), text.size = .75)+
  tm_layout(legend.position =c(0.65,0.9), 
            legend.text.size=.65, 
            legend.title.size = 1.1,
            frame=FALSE)+
  tm_credits("(c) OpenStreetMap contrbutors and Air b n b", position=c(0.0,0.0))+
  tm_compass(type = "8star", position = c(0.06, 0.1))+
  #tm_layout(inner.margins=0)
  tm_layout(inner.margin=c(0.04,0.04,0.04,0.4))
inset <- tm_shape(UK_outlinecrop)+
  tm_polygons(col="darkslategray1", lwd=1)+
  tm_shape(Londonbb)+
  tm_borders(col="grey40", lwd = 3)+
  tm_layout(frame=FALSE, bg.color="transparent")+
  tm_shape(Worldcities2)+
  tm_symbols(col = "red", scale = .5)+
  tm_text("city_name", xmod=-1.5, ymod=-0.5)
tmmain
print(inset,  vp = viewport(0.86, 0.29, width = 0.5, height = 0.55))

```

